name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build --no-cache -t web-demo .

      - name: Tag Docker image with commit SHA
        run: |
          docker tag web-demo:latest ${{ steps.login-ecr.outputs.registry }}/web-demo:${{ github.sha }}

      - name: Push Docker image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/web-demo:${{ github.sha }}

      - name: Update ECS Task Definition (Optional, if needed)
        # This step is only needed if you want to update the image in your task definition JSON
        run: |
          echo "Make sure your ECS task definition uses the image tag: ${{ github.sha }}"

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster cooperative-bee-v6rwk0 \
            --service testecs-service-zctsarr4 \
            --force-new-deployment \
            --region us-east-1
